baseurl = "https://example.org/"
languageCode = "en-us"
title = "Dorothy E. Davison Counselling Services"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

# You can use Markdown syntax for urls [text](//url.to/source) for
# most longer texts.

# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
# for more icons. The icons are represented by their corresponding
# CSS class.

# All projects of the portfolio are defined in their own files.
# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
# folder into the 'data' directory at the root of this Hugo site.
# For more information take a look at the README.

# To provide some metadata for search engines feel free to add some
# information about you and your website.
  name = "Dorothy E. Davison"
  description = "Dorothy Davison is a counselor based out of Kentville, Nova Scotia and offers support to those suffering from addiction, and those who are victims of abuse."

# The path must be relative to the static folder
  favicon = "favicon.ico"


# Navigation
[params.navigation]
  brand = "<span class=\"section\">Dorothy E. Davison</span> <span class=\"section\">Counselling Services</span>"

[params.navigation.links]
  about     = "About"
  services  = "Services"
  # portfolio = "Portfolio"
  contact   = "Contact"


# Hero section
[params.hero]
# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
  slogan     = "Dorothy E. Davison<br /> Counselling Services"
  subtitle   = "The support you need for a better tomorrow."
  buttonText = "Find out more"


# About section
[params.about]
  headline    = "About Dorothy"
  description = "Dorothy Davison is an accredited and certified counsellor based out of her home office in Kentville, Nova Scotia who has more than 20 years of experience providing relief to couples, families, and people suffering from addiction. Dorothy specializes in working with families who have grown up in homes with overt addiction, and acts as an advocate for those who have been physically, emotionally, sexually, or mentally abused. She has also attended workshops on gambling and internet addiction, and has been recognized by the Canadian Counselling Association with a pin commemorating 20 years of service."
  buttonText  = "Contact Dorothy"


# Service section
[params.services]
  headline = "At your service"

[[params.services.list]]
  icon = "fa-calendar-o"
  title = "Experience"
  description = "Dorothy Davison has been serving clients for more than 20 years."

[[params.services.list]]
  icon = "fa-home"
  title = "Privacy"
  description = "Dorothy's home office is in a quiet, secluded location that offers peace of mind."

[[params.services.list]]
  icon = "fa-usd"
  title = "Affordable Rates"
  description = "Sessions start at $90 for individuals, and $115 for couples."

[[params.services.list]]
  icon = "fa-briefcase"
  title = "Benefits"
  description = "Check with your EAP provider to see if Dorothy's services are covered by your plan."


# Portfolio modals
[params.portfolio.modal]
  client = "Client"
  date = "Date"
  category = "Category"
  buttonText = "Close"

# Aside section
[params.aside]
  headline = "See Dorothy's Professional Profile on LinkedIn"

[params.aside.button]
  text = "<i class=\"fa fa-linkedin-square\"></i> Dorothy Davison"
  link = "https://www.linkedin.com/in/dolly-davison-a2049239"

# Contact section
[params.contact]
  headline = "Contact Dorothy"
  description = "In these turbulent times, having the right support is more important than ever.<br> Call or email today and get the support you need."
  phone = "902-679-8578"
  email = "dorothydavison@eastlink.ca"

# Google Maps section
# [params.location]
# 	latitude  = "34.007850"
# 	longitude = "-118.499305"
# 	maps_api_key = ""
