baseurl = "https://example.org/"
languageCode = "en-us"
title = "Dorothy E. Davison Counselling Services"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

# You can use Markdown syntax for urls [text](//url.to/source) for
# most longer texts.

# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
# for more icons. The icons are represented by their corresponding
# CSS class.

# All projects of the portfolio are defined in their own files.
# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
# folder into the 'data' directory at the root of this Hugo site.
# For more information take a look at the README.

# To provide some metadata for search engines feel free to add some
# information about you and your website.
  name = "Dorothy E. Davison"
  description = "Your description"

# The path must be relative to the static folder
  favicon = "favicon.ico"


# Navigation
[params.navigation]
  brand = "<span class=\"section\">Dorothy E. Davison</span> <span class=\"section\">Counselling Services</span>"

[params.navigation.links]
  about     = "About"
  services  = "Services"
  portfolio = "Portfolio"
  contact   = "Contact"


# Hero section
[params.hero]
# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
  slogan     = "Your awesome slogan"
  subtitle   = "Dorothy Davison is an accredited and certified counsellor based out of her home office in Kentville, Nova Scotia. She has 20 years of experience providing relief to couples, families, and those who are suffering from addiction."
  buttonText = "Find out more"


# About section
[params.about]
  headline    = "About Dorothy"
  description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
  buttonText  = "Contact Dorothy"


# Service section
[params.services]
  headline = "At your service"

[[params.services.list]]
  icon = "fa-calendar-o"
  title = "Experience"
  description = "Dorothy Davison has been serving clients for more than 20 years."

[[params.services.list]]
  icon = "fa-paper-plane"
  title = "Ready to Ship"
  description = "You can use this theme as is, or you can make changes!"

[[params.services.list]]
  icon = "fa-usd"
  title = "Affordable Rates"
  description = "Sessions start at $90 for individuals, and $115 for couples."

[[params.services.list]]
  icon = "fa-briefcase"
  title = "Benefits"
  description = "Check with your EAP provider to see if Dorothy's services are covered by your plan."


# Portfolio modals
[params.portfolio.modal]
  client = "Client"
  date = "Date"
  category = "Category"
  buttonText = "Close"

# Aside section
[params.aside]
  headline = "See Dorothy's Professional Profile on LinkedIn"

[params.aside.button]
  text = "<i class=\"fa fa-linkedin-square\"></i> Dorothy Davison"
  link = "https://www.linkedin.com/in/dolly-davison-a2049239"

# Contact section
[params.contact]
  headline = "Contact Dorothy"
  description = "In these turbulent times, having the right support is more important than ever.<br> Call or email today and get the support you need."
  phone = "902-679-8578"
  email = "dorothydavison@eastlink.ca"

# Google Maps section
# [params.location]
# 	latitude  = "34.007850"
# 	longitude = "-118.499305"
# 	maps_api_key = ""
